### ISSUE TITLE
move away from soap library

### ISSUE THREAD

**Issue by thiccaxe** [StudentVue-Community/StudentVue.js#14]
the soap library doesn't seem to overly improve the developer experience. It might be better to simply roll a custom library. SOAP is very old and hardly used, cannot expect too many resources in case things to wrong with the PXPCommunications file etc.

**Comment by kaijchang** [comment]
@thiccaxe What do you mean by "roll a custom library"? SOAP is how the app communicates with the server, so it is "very old and hardly used," but there's not much you can do about that because that's the API that they provide that provides the best 1:1 replication of the app functionality. This library used to be web-scraping based, but that was a lot slower and more prone to breaking. Things won't "go wrong" with the PXPCommunications file unless they completely switch the protocol for their API.

**Comment by thiccaxe** [comment]
an update on this. PXPCommunications file doesn't have anything specific to it. Most of the useful stuff, Gradebook, ClassList, StudentInfo, etc. is not available there. however, it seems that we can get away with not using xml in the request. it seems we can make an http post request. will reduce code complexity. I will update again once I have tested much more.
