### ISSUE TITLE
StudentVue backend update?

### ISSUE THREAD

**Issue by Rayn322** [StudentVue-Community/StudentVue.js#19]
Logging in throws an error with the message `We have upgraded our server for better performance. You must update app to the new version to continue.`

I'm not sure if this is something that is on a per-district basis so I'm curious if anyone else is getting this error.

**Comment by Rayn322** [comment]
The mobile app updated a week ago with "urgent update related to login" as the patch notes so yeah

**Comment by thiccaxe** [comment]
@Rayn322 I did some research, and what I believe is the case is that the "We have upgraded our server for better performance. You must update app to the new version to continue" is a bogus message. It seems that the synergy instance in question has disabled username-and-password login, and only allows staff and students to login using saml (google, in this case). TLDR: this library is useless for the synergy instance in question.

My suspicion is that the instance implemented this change for the 2023-2024 school year, then noticed that on the mobile app version at the time, the username-and-password method was still visible. This likely led to confusion, as people were unexpectedly unable to log in using username-and-password from the app. The administrators of the synergy instance in question likely contacted edupoint about this issue, at which point edupoint released the "urgent update related to login" update. In order to efficiently get users of the app to update, the administrators of the synergy instance in question likely configured the bogus error message. There is likely no connection between a newer version of Synergy SIS and the inability to use username-and-password login. This is not to attack the decisions of the administrators of the synergy instance in question, but rather my attempt to explain why such an unusual error message could appear and how it might prevent this library from working. And anyway, take this all with a grain of salt.
